<?php

namespace App\Account\Application\Command\Account;

use App\Shared\Application\Command\CommandInterface;
use Money\Currency;

final readonly class CreateAccountCommand implements CommandInterface
{
    public function __construct(
        public int $id, // uuid or generated by Doctrine then don't have to set it here
        public Currency $currency,
    ) {
    }
}
